spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Security Configuration
jwt.secret=aAPTVapPIW5Xx9W0vXiol2rEDAZwBjt4jGgenGXWv5xjmFlyaa63MQcg0mhCD3YdOlzrXqdaAdXFnTSwh3x8g
jwt.expiration=3600000